license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}/mixins/battle/presentation.json"

[[mixins]]
config="${mod_id}/mixins/dimension/snowdin/entity/monster_npc.json"

[[mixins]]
config="${mod_id}/mixins/content/player/soul.json"

[[mixins]]
config="${mod_id}/mixins/dimension/ebott/transition.json"

[[mixins]]
config="${mod_id}/mixins/dimension/snowdin.json"

[[mixins]]
config="${mod_id}/mixins/dimension/worldgen.json"

[[mixins]]
config="${mod_id}/mixins/dimension/region/core.json"

[[mixins]]
config="${mod_id}/mixins/magic/karma.json"

[[mixins]]
config="${mod_id}/mixins/magic/screen_door.json"

[[mixins]]
config="${mod_id}/mixins/magic/beam_composite.json"

[[mixins]]
config="${mod_id}/mixins/magic/camera_shake.json"

[[mixins]]
config="${mod_id}/mixins/voxel/scene.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="geckolib"
type="required"
versionRange="[${geckolib_version},)"
ordering="AFTER"
side="BOTH"
